name: Rodar Pipeline
on:
  pull_request:
    paths:
      - '**/*.swift'


jobs:
  build: 
    name: Build Project 
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: intall dependencies
      run: pod install --project-directory=./AppMVVM

    - name: Clean & Build & Test
      run: xcodebuild clean build -workspace AppMVVM/AppMVVM.xcworkspace -scheme AppMVVM CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,OS=16.4,name=Any iOS Simulator Device" ONLY_ACTIVE_ARCH=YES
